export const selections = [
  "sofas",
  "center tables",
  "bedframes",
  "dining sets",
  "chairs",
];

export const dimension = [
  { property: "Height", tag: "height" },
  { property: "Length", tag: "lengthh" },
  { property: "Width", tag: "width" },
  { property: "Seat Height", tag: "seatHeight" },
  { property: "Seat Depth", tag: "seatDepth" },
  { property: "Seat Width", tag: "seatWidth" },
  { property: "Net Seat Height", tag: "seatHeightFloor" },
  { property: "Arm Rest Height", tag: "armRestHeightAboveSeat" },
  { property: "Arm Rest Length", tag: "armRestLength" },
  { property: "Seat Back Height", tag: "seatBackHeight" },
  { property: "Table Width", tag: "tableWidth" },
  { property: "Table Length", tag: "tableLength" },
  { property: "Table Height", tag: "tableHeight" },
  { property: "OtterMan Width", tag: "otterManWidth" },
  { property: "OtterMan Height", tag: "otterManHeight" },
  { property: "OtterMan Length", tag: "otterManLength" },
];

export const productCatalogue = [
  {
    id: "1",
    image: "images/bedFrames/Group 11.webp",
    type: "bedframes",
    name: "The Floating Saucer",
    description:
      "The Floating Saucer features a floating wooden platform design constructed. It includes an integrated headboard with recessed shelving and two attached, cantilevered nightstands.",
    dimensions: {
      height: "",
      lengthh: '82"',
      width: '67"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "2",
    image: "images/bedFrames/Group 17.webp",
    type: "bedframes",
    name: "The Minimal Stance",
    description:
      "The Minimal Stance features a classic slatted design constructed from light-toned wood. It includes a rectangular headboard and footboard, with the footboard exhibiting a horizontal recessed detail. The side rails are solid, and the frame is elevated on integrated wooden block legs.",
    dimensions: {
      height: "",
      lengthh: '78"',
      width: '61"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "3",
    image: "images/bedFrames/Group 14.webp",
    type: "bedframes",
    name: "Checkerboard Orb Solace",
    description:
      "Thhe Checkerboard Orb Solace bed frame features a wooden base supported by four prominent spherical wooden feet. The headboard is a distinctive, horizontally elongated oval shape, composed of contrasting wooden panels arranged in a checkerboard pattern",
    dimensions: {
      height: "",
      lengthh: '76"',
      width: '60"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Mahogany Wood"],
    colors: [],
  },
  {
    id: "4",
    image: "images/bedFrames/Group 15.webp",
    type: "bedframes",
    name: "The Regal Arched Bed",
    description:
      "The Regal Arched Bed frame features a traditional design with a dark-stained wooden structure. Both the headboard and footboard are upholstered with a plain-woven fabric and feature a curved, arched top profile. The frame incorporates four turned wooden posts, each topped with a decorative finial.",
    dimensions: {
      height: "",
      lengthh: '77"',
      width: '61"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Masonia Wood"],
    colors: [],
  },
  {
    id: "5",
    image: "images/bedFrames/Group 16.webp",
    type: "bedframes",
    name: "Grandeur Modern Floating Bed",
    description:
      "The Grandeur Modern Floating Bed frame features an integrated wooden headboard with upholstered panels. Two cantilevered wooden nightstand is attached to one side of the headboard. The platform extends beyond the mattress perimeter.",
    dimensions: {
      height: "",
      lengthh: '81"',
      width: '66"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Masonia Wood"],
    colors: [],
  },
  {
    id: "6",
    image: "images/bedFrames/Group 20.webp",
    type: "bedframes",
    name: "The Modern Bloc",
    description:
      "The Modern Bloc bed frame features a upholstered, rectangular headboard panel and the footboard is a simple, solid wooden panel.",
    dimensions: {
      height: "",
      lengthh: '76"',
      width: '60"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "7",
    image: "images/bedFrames/Group 18.webp",
    type: "bedframes",
    name: "The Manor Arched Gable",
    description:
      "The Manor Arched Gable bed frame features a dark-stained wooden structure with a prominent, arched headboard and footboard. The frame incorporates four turned wooden posts, each topped with a decorative finial.",
    dimensions: {
      height: "",
      lengthh: '78"',
      width: '62"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "8",
    image: "images/bedFrames/Group 19.webp",
    type: "bedframes",
    name: "The Pillow-Back Refuge",
    description:
      "The Pillow-Back Refuge bed frame features a upholstered platform base with integrated storage drawers on the side. The headboard is also fully upholstered, comprising two distinct, plush-looking panels.",
    dimensions: {
      height: "",
      lengthh: '79"',
      width: '62"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Leather Textile, Masonia Wood"],
    colors: ["#af875d", "#2f2f2f"],
  },
  {
    id: "9",
    image: "images/bedFrames/Group 13.webp",
    type: "bedframes",
    name: "Integrated Executive Lift-Top",
    description:
      "The Integrated Executive Lift-Top bed frame is a highly integrated storage unit that features a lift-up mattress platform revealing extensive under-bed compartments. The headboard is also multi-functional, incorporating upholstered panels, concealed storage sections that flip open, and a built-in shelf. Two pull-out drawers are integrated into the footboard.",
    dimensions: {
      height: "",
      lengthh: '81"',
      width: '68"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Mahogany Wood"],
    colors: [],
  },
  {
    id: "10",
    image: "images/bedFrames/Group 54.webp",
    type: "bedframes",
    name: "Wide Deck Winged Saucer",
    description:
      "The Wide Deck Winged Saucer bed frame features a minimalist, floating platform design that includes an integrated, rectangular wooden headboard. Two extended, cantilevered wooden nightstands are attached to the headboard, extending significantly beyond the bed's width. ",
    dimensions: {
      height: "",
      lengthh: '84"',
      width: '68"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "11",
    image: "images/centerTables/Group 4.webp",
    type: "center tables",
    name: "The Forever Parallel",
    description:
      "The Forever Parallel features two-tiered, rectangular wooden slab panels. The upper slab is supported by a central, vertical wooden panel that also forms part of the lower structure, creating an open-ended design. ",
    dimensions: {
      height: '28"',
      lengthh: '28"',
      width: '19"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Mahogany Wood"],
    colors: [],
  },
  {
    id: "12",
    image: "images/centerTables/Group 9.webp",
    type: "center tables",
    name: "Otherworld Otterman",
    description:
      "The Otherworld Otterman features a sculptural, angular design with a long rectangular top surface. The body is constructed from flat wooden panels, forming an open, trapezoidal volume with an internal shelf. The sides are slanted, giving the piece a dynamic, cantilevered appearance.",
    dimensions: {
      height: '17"',
      lengthh: '26"',
      width: '22"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Mahogany Wood"],
    colors: [],
  },
  {
    id: "13",
    image: "images/centerTables/Group 2.webp",
    type: "center tables",
    name: "The Pillar & Pod",
    description:
      "The Pillar & Pod features two distinct elements: a cylindrical wooden pedestal base on one end, and an integrated, curved wooden storage module containing a single drawer on the other.",
    dimensions: {
      height: '18"',
      lengthh: '30"',
      width: "20",
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      materials: ["Mahogany Wood"],
      tableHeight: "",
    },
    materials: [],
    colors: [],
  },
  {
    id: "14",
    image: "images/centerTables/Group 62.webp",
    type: "center tables",
    name: "Greg Offset Interlock",
    description:
      "The Greg Offset Interlock is a multi-component unit. Its primary unit is a low-profile base with two integrated drawers, featuring rounded corners, whie the secondary unit is a smaller square wooden module positioned atop and perpendicular to one end of the primary module, creating a stepped, overlapping surface.",
    dimensions: {
      height: '20"',
      lengthh: '33"',
      width: '19"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Masonia Wood"],
    colors: [],
  },
  {
    id: "15",
    image: "images/centerTables/Group 5.webp",
    type: "center tables",
    name: "Apex Origami",
    description:
      "The Apex Origami features a striking geometric design, constructed from flat wooden panels. It has a single, rectangular top surface supported by a V-shaped base that also forms an open storage shelf. The base connects to the floor via a small, central support panel, creating an inverted triangular void on one side.",
    dimensions: {
      height: '19"',
      lengthh: '28"',
      width: '20"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Mahogany Wood"],
    colors: [],
  },
  {
    id: "16",
    image: "images/centerTables/Group 6.webp",
    type: "center tables",
    name: "The Sideless Cube",
    description:
      "The Sideless Cube features a two-tiered, square structure constructed from flat wooden panels. The upper tier is supported by two short, perpendicular vertical panels that connect it to the lower tier, creating an open, minimalist design.",
    dimensions: {
      height: '19"',
      lengthh: '22"',
      width: '22"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Masonia Wood"],
    colors: [],
  },
  {
    id: "17",
    image: "images/centerTables/Group 7.webp",
    type: "center tables",
    name: "The Assymetric Floating Top",
    description:
      "The Assymetric Floating Top table incorporates an open storage compartment and a single pull-out drawer, both integrated into the body of the table.",
    dimensions: {
      height: '19"',
      lengthh: '28"',
      width: '19"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "18",
    image: "images/centerTables/Group 8.webp",
    type: "center tables",
    name: "The Slide & Store Centerpiece",
    description:
      "The Slide & Store Centerpiece features a complex, asymmetrical structure composed of several wooden modules. It includes a lower, rectangular base with two drawers and an open shelving unit. Extending from this, a longer, thinner top surface cantilevers over a separate, open shelving unit that forms the opposite end support. The design incorporates multiple storage compartments and varied surface levels.",
    dimensions: {
      height: '22"',
      lengthh: '33"',
      width: '19"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "19",
    image: "images/centerTables/Group 3.webp",
    type: "center tables",
    name: "The Bean Peach",
    description:
      "The Bean Peach features a bean-shaped, irregular oval wooden top surface with rounded edges. It is supported by four robust, cylindrical wooden legs, positioned directly beneath the table's perimeter.",
    dimensions: {
      height: '20"',
      lengthh: '27"',
      width: '18"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "20",
    image: "images/centerTables/Group 10.webp",
    type: "center tables",
    name: "The Butterfly Effect",
    description:
      "The Butterfly Effect consists of two half pieces forming the shape of a butterfly as a whole. Both set is supported by two short, almost converging wooden slabs.",
    dimensions: {
      height: '17"',
      lengthh: '20"',
      width: '19"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "21",
    image: "images/centerTables/Group 52.webp",
    type: "center tables",
    name: "The Ying-Yang",
    description:
      "The Ying-Yang modular coffee table consists of two interlocking sets. Each table has a solid, continuous wooden top and base, connected by a vertical panel. The design allows the two units to nest or be separated, forming varied configurations.",
    dimensions: {
      height: '18"',
      lengthh: '31"',
      width: '19"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "22",
    image: "images/centerTables/Group 59.webp",
    type: "center tables",
    name: "The C-Frame Embrace",
    description:
      "The C-Frame Embrace features an 'C'-shaped wooden frame, forming a top surface and a base connected by a continuous curved panel. Nested within this frame is a separate, rectangular wooden storage unit with two drawers.",
    dimensions: {
      height: '19"',
      lengthh: '26"',
      width: '20"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Mahogany Wood"],
    colors: [],
  },
  {
    id: "23",
    image: "images/sofas/Group 60.webp",
    type: "sofas",
    name: "The Beamline Open Frame",
    description:
      "The Beamline Open Frame consists of an external open wooden frame, forming both the base and outer arm supports. Two independent upholstered seat and back units are nested within this framework.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '8"',
      seatDepth: '19"',
      overallDepth: "",
      seatWidth: '51"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: '6"',
      armRestLength: '27"',
      seatBackHeight: '14"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Iroko Wood"],
    colors: ["#6f6f6f", "#2f2f2f", "#ffffff"],
  },
  {
    id: "24",
    image: "images/sofas/Group 21.webp",
    type: "sofas",
    name: "Shadow Line Sectional sofa",
    description:
      "The Shadow Line Sectional sofa comprises multiple fully upholstered modules, it features seat and back cushions with distinct edge seams.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '11"',
      seatDepth: '21"',
      overallDepth: "",
      seatWidth: '76"',
      seatHeightFloor: '17"',
      armRestHeightAboveSeat: '6"',
      armRestLength: '31"',
      seatBackHeight: '16"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Masonia Wood"],
    colors: ["#6f6f6f", "#ffffff", "#af875d", "#000240"],
  },
  {
    id: "25",
    image: "images/sofas/Group 25.webp",
    type: "sofas",
    name: "Elders Haven",
    description:
      "The Elders Haven sofa features an 'L'-shaped configuration, constructed with an exposed, wooden frame defining the base, arms, and back. It comprises four distinct seat cushions and a separate chaise lounge module.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '9"',
      seatDepth: '20"',
      overallDepth: "",
      seatWidth: '74"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: '6"',
      armRestLength: '26"',
      seatBackHeight: '16"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Iroko Wood"],
    colors: ["#ffffff", "#af875d"],
  },
  {
    id: "26",
    image: "images/sofas/Group 56.webp",
    type: "sofas",
    name: "Urban Studio Sofa",
    description:
      "The Urban Studio Sofa two-seater sofa presents a fully upholstered, monolithic form with integrated arms and back, creating a continuous rounded profile. It features two distinct seat cushions.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '8"',
      seatDepth: '18"',
      overallDepth: "",
      seatWidth: '53"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: '8"',
      armRestLength: '23"',
      seatBackHeight: '14"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Leather Textile", "Masonia Wood"],
    colors: ["#af875d", "#6f6f6f", "#3e0212"],
  },
  {
    id: "27",
    image: "images/sofas/Group 35.webp",
    type: "sofas",
    name: "The Mid-Century Retreat",
    description:
      "The Mid-Century Retreat features an exposed wooden frame defining the base, back, and arm supports. The seating and backrest are integrated, tufted units. It includes a single chaise lounge module.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '9"',
      seatDepth: '20"',
      overallDepth: "",
      seatWidth: '76"',
      seatHeightFloor: '17"',
      armRestHeightAboveSeat: '9"',
      armRestLength: '25"',
      seatBackHeight: '14"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Leather Textile", "Mahogany Wood"],
    colors: ["#3e0212", "#ffffff"],
  },
  {
    id: "28",
    image: "images/sofas/Group 12.webp",
    type: "sofas",
    name: "Drawer Dweller Oasis",
    description:
      "The Drawer Dweller Oasis integrates directly onto a large, exposed wooden base frame. The base features multiple pull-out storage drawers and an integrated, open-shelf storage module on one end, serving as an armrest. The seating consists of independent seat and back cushions.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '20"',
      overallDepth: "",
      seatWidth: '51"',
      seatHeightFloor: '17"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '15"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Masonia Wood"],
    colors: ["#2f2f2f", "#6f6f6f"],
  },
  {
    id: "29",
    image: "images/sofas/Group 31.webp",
    type: "sofas",
    name: "The Plush Pebble Base",
    description:
      "The Plush Pebble Base sofa features backrest and tufted seat cushions that are integrated. It is supported by large, spherical wooden feet.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '8"',
      seatDepth: '20"',
      overallDepth: "",
      seatWidth: '52"',
      seatHeightFloor: '17"',
      armRestHeightAboveSeat: "",
      armRestLength: '22"',
      seatBackHeight: '14"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Mahogany Wood"],
    colors: ["#6f6f6f", "#ffffff"],
  },
  {
    id: "30",
    image: "images/sofas/Group 55.webp",
    type: "sofas",
    name: "The Horizon Hideaway",
    description:
      "The Horizon Hideaway features an exposed wooden frame with an integrated storage unit containing two drawers beneath the seat. It includes separate seat cushions, back cushions, and detached, upholstered armrest bolsters.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '6"',
      seatDepth: '18"',
      overallDepth: "",
      seatWidth: '48"',
      seatHeightFloor: '18"',
      armRestHeightAboveSeat: "",
      armRestLength: '24"',
      seatBackHeight: '16"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Masonia Wood"],
    colors: ["#af875d", "#2f2f2f"],
  },
  {
    id: "31",
    image: "images/sofas/Group 37.webp",
    type: "sofas",
    name: "Arden Fluid-Form Sofa",
    description:
      "The Arden Fluid-Form Sofa is composed of multiple fully upholstered units, including rounded end modules. The entire structure is low-profile and rests directly on the floor with concealed feet. Seating and backrests are integrated into the continuous upholstered form.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '18"',
      overallDepth: "",
      seatWidth: '71"',
      seatHeightFloor: '14"',
      armRestHeightAboveSeat: '6"',
      armRestLength: "",
      seatBackHeight: '12"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Masonia Wood"],
    colors: ["#ffffff", "#6f6f6f", "#2f2f2f"],
  },
  {
    id: "32",
    image: "images/sofas/Group 40.webp",
    type: "sofas",
    name: "Grace Lounge Ensemble",
    description:
      "The Grace Lounge Ensemble sofa comprises multiple modules, with a long main sofa section and a rounded chaise lounge. It is supported by slender, tapered wooden legs. The seating includes separate seat cushions and loose back cushions. ",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '8"',
      seatDepth: '21"',
      overallDepth: "",
      seatWidth: '72"',
      seatHeightFloor: "72",
      armRestHeightAboveSeat: '8"',
      armRestLength: '28"',
      seatBackHeight: '12"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Mahogany Wood"],
    colors: ["#ffffff", "#6f6f6f", "#2f2f2f"],
  },
  {
    id: "33",
    image: "images/sofas/Group 27.webp",
    type: "sofas",
    name: "Stow Connect Sofa",
    description:
      "The Stow Connect Sofa is a three-seater sofa unit  that has a separate chaise lounge, it also features exposed wooden frame bases and legs. An integrated wooden side table with shelves connects the two units. The chaise lounge also incorporates an additional wooden surface at its far end.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '7"',
      seatDepth: '18"',
      overallDepth: "",
      seatWidth: '50"',
      seatHeightFloor: '15"',
      armRestHeightAboveSeat: '7"',
      armRestLength: '26"',
      seatBackHeight: '15"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Masonia Wood"],
    colors: ["#af875d", "#ffffff"],
  },
  {
    id: "34",
    image: "images/sofas/Group 23.webp",
    type: "sofas",
    name: "The Integrated Settle",
    description:
      "The Integrated Settle features a prominent, dark-stained exposed wooden frame defining the base, arms, and back perimeter. Integrated wooden storage modules with shelving are present at both ends of the sofa.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '8"',
      seatDepth: '20"',
      overallDepth: "",
      seatWidth: '89"',
      seatHeightFloor: '15"',
      armRestHeightAboveSeat: '6"',
      armRestLength: '28"',
      seatBackHeight: '16"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Mahogany Wood"],
    colors: ["#6f6f6f", "#ffffff"],
  },
  {
    id: "35",
    image: "images/sofas/Group 57.webp",
    type: "sofas",
    name: "The Signature Armroll Sofa",
    description:
      "The Signature Armroll Sofa features a fully upholstered box-frame structure with straight track arms and a low back. It includes two independent seat cushions, two loose back cushions, and two cylindrical bolster pillows.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '7"',
      seatDepth: '18"',
      overallDepth: "",
      seatWidth: '52"',
      seatHeightFloor: '15"',
      armRestHeightAboveSeat: '6"',
      armRestLength: '24"',
      seatBackHeight: '15"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Masonia Wood"],
    colors: ["#2f2f2f", "#6f6f6f"],
  },
  {
    id: "36",
    image: "images/sofas/Group 58.webp",
    type: "sofas",
    name: "The Pin-Tuck Retro Sofa",
    description:
      "The Pin-Tuck Retro Sofa features a fully upholstered frame with gently sloped arms and a slightly elevated backrest. It includes two distinct seat cushions and two loose back cushions with button-tufted detailing. ",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '7"',
      seatDepth: '18"',
      overallDepth: "",
      seatWidth: '52"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: '6"',
      armRestLength: '26"',
      seatBackHeight: '13"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: ["Fabric Textile", "Masonia Wood"],
    colors: ["#2f2f2f", "#6f6f6f", "#ffffff"],
  },
  {
    id: "37",
    image: "images/diningSets/Group 41.webp",
    type: "dining sets",
    name: "Arched Ladder-Back Set",
    description:
      "The Arched Ladder-Back Set comprises a round pedestal table and four dining chairs, all constructed from light-toned wood. The table features a solid, conical pedestal base supporting a circular top. Each chair has a tall slanted back-rest.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '16"',
      overallDepth: "",
      seatWidth: '15"',
      seatHeightFloor: '17"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '16"',
      tableWidth: '39"',
      tableHeight: '29"',
      tableLength: "",
    },
    materials: ["Masonia Wood"],
    colors: [],
  },
  {
    id: "38",
    image: "images/diningSets/Group 44.webp",
    type: "dining sets",
    name: "Tuck-Away Interlock Set",
    description:
      "The Tuck-Away Interlock Set features a round wooden table designed for compact storage. Six chairs are designed to perfectly nest within the perimeter of the table when not in use. The chairs feature curved backrests.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '15"',
      overallDepth: "",
      seatWidth: '14"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '13"',
      tableWidth: '40"',
      tableHeight: '30"',
      tableLength: "",
    },
    materials: ["Masonia Wood"],
    colors: [],
  },
  {
    id: "39",
    image: "images/diningSets/Group 43.webp",
    type: "dining sets",
    name: "Retro Close-Quater Set",
    description:
      "The Retro Close-Quater Set includes a square wooden table supported by four tapered wooden legs. It is accompanied by four fully upholstered dining chairs. Each chair features a continuous, rounded backrest and seat, elevated on four slender, angled wooden legs",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '16"',
      overallDepth: "",
      seatWidth: '15"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '14"',
      tableWidth: '39"',
      tableHeight: '31"',
      tableLength: "40",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "40",
    image: "images/diningSets/Group 51.webp",
    type: "dining sets",
    name: "Fluted Supper Collective Set",
    description:
      "The Fluted Supper Collective Set features an oval table supported by two fluted cylindrical base. It is accompanied by six dining chairs, each with a dark-stained wooden frame and legs. The chairs have upholstered seats and rounded, upholstered backrests, accented by a horizontal wooden bar across the upper back.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '16"',
      overallDepth: "",
      seatWidth: '15"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '15"',
      tableWidth: '41"',
      tableHeight: '31"',
      tableLength: '60"',
    },
    materials: ["Mahogany Wood"],
    colors: [],
  },
  {
    id: "41",
    image: "images/diningSets/Group 46.webp",
    type: "dining sets",
    name: "Arboreal Ribbed Cascade Set",
    description:
      "The Arboreal Ribbed Cascade Set features a rectangular wooden table with a distinct, sculptural base composed of multiple curved and vertical wooden slats, forming a unique architectural support. It is accompanied by four chairs, each with a wooden frame forming a continuous curved shape for the legs and back. The chairs have upholstered seats and circular, upholstered backrests.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '15"',
      overallDepth: "",
      seatWidth: '15"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '16"',
      tableWidth: '41"',
      tableHeight: '31"',
      tableLength: '51"',
    },
    materials: ["Mahogany Wood"],
    colors: [],
  },
  {
    id: "42",
    image: "images/diningSets/Group 47.webp",
    type: "dining sets",
    name: "Nesting Nook Set",
    description:
      "The Nesting Nook Set features a square wooden table with a central pedestal base that incorporates open shelving. It is designed to house four matching cubic stools with upholstered tops, which nest perfectly beneath the tabletop.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: '15"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: '37"',
      tableHeight: '31"',
      tableLength: '39"',
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
  {
    id: "43",
    image: "images/diningSets/Group 48.webp",
    type: "dining sets",
    name: "Circle-Back Retro Set",
    description:
      "The Circle-Back Retro Set features an oval wooden table supported by two solid, rectangular wooden slab bases. It is accompanied by four chairs, each with a wooden frame forming a continuous curved shape for the legs and back. The chairs have upholstered seats and circular, upholstered backrests.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '15"',
      overallDepth: "",
      seatWidth: '15"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '16"',
      tableWidth: '41"',
      tableHeight: '31"',
      tableLength: '60"',
    },
    materials: ["Masonia Wood"],
    colors: [],
  },
  {
    id: "44",
    image: "images/diningSets/Group 49.webp",
    type: "dining sets",
    name: "Barrel-Back Set",
    description:
      "The Barrel-Back Set features a rectangular table constructed from light-toned wood. The chairs have upholstered seats and distinctive, cylindrical upholstered backrests held by wooden straps",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '16"',
      overallDepth: "",
      seatWidth: '15"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '15"',
      tableWidth: '41"',
      tableHeight: '31"',
      tableLength: '60"',
    },
    materials: ["Mahogany Wood"],
    colors: [],
  },
  {
    id: "45",
    image: "images/chairs/Group 22.webp",
    type: "chairs",
    name: "Tulip Splay",
    description:
      "The Tulip Splay features a upholstered continuous shell forming the seat, back, and arms, characterized by a rounded. It is supported by four slender, angled wooden legs.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '15"',
      overallDepth: "",
      seatWidth: '16"',
      seatHeightFloor: '17"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '14"',
      tableWidth: "",
      tableHeight: "",
      tableLength: "",
    },
    materials: ["Fabric Textile", "Iroko Wood"],
    colors: ["#af875d", "#2f2f2f"],
  },
  {
    id: "46",
    image: "images/chairs/Group 36.webp",
    type: "chairs",
    name: "Ergo-Sway Gravity Glide",
    description:
      "The Ergo-Sway Gravity Glide features a wooden frame with continuous curved rockers. It has an extended seat and backrest design, forming a reclining lounge shape. The frame supports plush upholstered cushions that cover the entire seating and back area.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '17"',
      overallDepth: "",
      seatWidth: '16"',
      seatHeightFloor: '14"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '16"',
      tableWidth: "",
      tableHeight: "",
      tableLength: "",
    },
    materials: ["Fabric Textile", "Mahogany Wood"],
    colors: ["#2f2f2f", "#6f6f6f"],
  },
  {
    id: "47",
    image: "images/chairs/Group 32.webp",
    type: "chairs",
    name: "Lambda Cradle Arm-Chair",
    description:
      "The Lambda Cradle Arm-Chair features a distinctive exposed wooden frame, with curved, intersecting side panels that form both the arms and legs. A rectangular upholstered seat cushion and backrest cushion, along with a lumbar pillow, are set within this frame.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '15"',
      overallDepth: "",
      seatWidth: '17"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '15"',
      tableWidth: "",
      tableHeight: "",
      tableLength: "",
    },
    materials: ["Fabric Textile", "Iroko Wood"],
    colors: ["#2f2f2f", "#6f6f6f"],
  },
  {
    id: "48",
    image: "images/chairs/Group 34.webp",
    type: "chairs",
    name: "Snuggly Cozy Glide",
    description:
      "The Snuggly Cozy Glide features a wooden frame with continuous curved rockers and armrests. It supports a voluminous, multi-sectioned upholstered cushion set that covers the seat, back, and headrest, accompanied by a small lumbar pillow",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '18"',
      overallDepth: "",
      seatWidth: '16"',
      seatHeightFloor: '18"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '16"',
      tableWidth: "",
      tableHeight: "",
      tableLength: "",
    },
    materials: ["Leather Textile", "Mahogany Wood"],
    colors: ["#af875d", "#2f2f2f"],
  },
  {
    id: "49",
    image: "images/chairs/Group 30.webp",
    type: "chairs",
    name: "The Macaron Pod",
    description:
      "The Macaron Pod features two stacked, cylindrical upholstered cushions separated by a visible wooden ring frame. The entire unit is supported by four slender, exposed wooden legs that extend through the upper cushion and frame the sides.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: '16"',
      seatHeightFloor: '15"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
      tableLength: "",
    },
    materials: ["Fabric Textile", "Iroko Wood"],
    colors: ["#ffffff", "#2f2f2f"],
  },
  {
    id: "50",
    image: "images/chairs/Group 61.webp",
    type: "chairs",
    name: "The Accent Stool",
    description:
      "The Accent Stool is fully upholstered with a smooth forming a continuous curved shell that cradles a rectangular, independent upholstered cushion. It is supported by four tapered wooden legs",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: '17"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
      tableLength: "",
    },
    materials: [],
    colors: ["#6f6f6f"],
  },
  {
    id: "51",
    image: "images/chairs/Group 33.webp",
    type: "chairs",
    name: "Single Mid-Century Retreat",
    description:
      "The Single Mid-Century Retreat has a wooden box frame that defines the arms and back. Within this frame are a single seat cushion and a tufted backrest, both fully upholstered.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: '9"',
      seatDepth: '20"',
      overallDepth: "",
      seatWidth: '26"',
      seatHeightFloor: '17"',
      armRestHeightAboveSeat: '9"',
      armRestLength: '25"',
      seatBackHeight: '14"',
      tableWidth: "",
      tableHeight: "",
    },
    materials: [],
    colors: ["#3e0212", "#ffffff"],
  },
  {
    id: "52",
    image: "images/chairs/Group 24.webp",
    type: "chairs",
    name: "Grand Regent Set",
    description:
      "The Grand Regent Set comprises a rocking chair and a matching ottoman, both with dark-stained wooden frames. The rocking chair features curved rockers and ornate, scrolled wooden arms. Both the chair and ottoman have deeply tufted, upholstered cushions.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '18"',
      overallDepth: "",
      seatWidth: '16"',
      seatHeightFloor: '17"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '16"',
      tableWidth: "",
      tableHeight: "",
      tableLength: "",
      otterManWidth: '14"',
      otterManHeight: '16"',
      otterManLength: '16"',
    },
    materials: [],
    colors: ["#3e0212", "#2f2f2f", "#af875d"],
  },
  {
    id: "53",
    image: "images/chairs/Group 28.webp",
    type: "chairs",
    name: "The Cloud Comfort",
    description:
      "The Cloud Comfort features a minimalist frame and an upholstered cushion. The backrest is a continuous, curved upholstered shell that also forms integrated armrests with a distinctive rolled profile.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '15"',
      overallDepth: "",
      seatWidth: '17"',
      seatHeightFloor: '17"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '14"',
      tableWidth: "",
      tableHeight: "",
      tableLength: "",
    },
    materials: [],
    colors: ["#ffffff", "#2f2f2f"],
  },
  {
    id: "54",
    image: "images/chairs/Group 39.webp",
    type: "chairs",
    name: "Double C-Curve Compact",
    description:
      "The Double C-Curve Compact features a fully upholstered, rounded bucket-style seat and back, with visible wooden side panels that form its base and extend upwards to frame the outer arms.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '15"',
      overallDepth: "",
      seatWidth: '16"',
      seatHeightFloor: '16"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '12"',
      tableWidth: "",
      tableHeight: "",
      tableLength: "",
    },
    materials: [],
    colors: ["#6f6f6f", "#ffffff"],
  },
  {
    id: "55",
    image: "images/chairs/Group 26.webp",
    type: "chairs",
    name: "Classic Heirloom Glide",
    description:
      "The Classic Heirloom Glide features a traditional, ornate design that includes intricately carved crest rail, vertical spindles in the backrest, and turned armrests and supports. The base consists of classic curved rockers.",
    dimensions: {
      height: "",
      lengthh: "",
      width: "",
      seatHeight: "",
      seatDepth: '15"',
      overallDepth: "",
      seatWidth: '16"',
      seatHeightFloor: '17"',
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: '17"',
      tableWidth: "",
      tableHeight: "",
      tableLength: "",
    },
    materials: [],
    colors: ["#af875d", "#2f2f2f"],
  },
  {
    id: "56",
    image: "images/centerTables/Group 1.webp",
    type: "center tables",
    name: "The Duet Floating Top",
    description:
      "The Duet Floating Top features a rectangular wooden top with rounded corners, elevated above a wooden base. The base contains a single pull-out drawer with a rounded face and an open storage shelf above it.",
    dimensions: {
      height: '19"',
      lengthh: '27"',
      width: '20"',
      seatHeight: "",
      seatDepth: "",
      overallDepth: "",
      seatWidth: "",
      seatHeightFloor: "",
      armRestHeightAboveSeat: "",
      armRestLength: "",
      seatBackHeight: "",
      tableWidth: "",
      tableHeight: "",
      tableLength: "",
    },
    materials: ["Iroko Wood"],
    colors: [],
  },
];
